###### This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [76]:
df=pd.read_csv("/kaggle/input/restaurant-revenue-prediction-dataset/restaurant_data.csv")

In [77]:
df

,Name,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Marketing Budget,Social Media Followers,Chef Experience Years,Number of Reviews,Avg Review Length,Ambience Score,Service Quality Score,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,Restaurant 0,Rural,Japanese,4.0,38,73.98,2224,23406,13,185,161.924906,1.3,7.0,Yes,13,4,638945.52
1,Restaurant 1,Downtown,Mexican,3.2,76,28.11,4416,42741,8,533,148.759717,2.6,3.4,Yes,48,6,490207.83
2,Restaurant 2,Rural,Italian,4.7,48,48.29,2796,37285,18,853,56.849189,5.3,6.7,No,27,14,541368.62
3,Restaurant 3,Rural,Italian,4.4,34,51.55,1167,15214,13,82,205.433265,4.6,2.8,Yes,9,17,404556.80
4,Restaurant 4,Downtown,Japanese,4.9,88,75.98,3639,40171,9,78,241.681584,8.6,2.1,No,37,26,1491046.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8363,Restaurant 8363,Suburban,Indian,3.4,54,34.85,1102,11298,11,380,253.919515,9.5,5.0,Yes,37,0,434653.45
8364,Restaurant 8364,Rural,Indian,3.7,49,36.88,1988,20432,9,713,175.590195,2.7,2.6,No,37,21,414977.92
8365,Restaurant 8365,Downtown,Italian,4.7,88,46.87,5949,63945,6,436,222.953647,4.8,1.7,Yes,83,21,930395.87
8366,Restaurant 8366,Rural,American,3.1,31,44.53,707,7170,1,729,178.482851,6.1,2.1,No,6,21,311493.48
8367,Restaurant 8367,Rural,Japanese,4.0,33,71.07,2003,24268,8,197,151.838065,5.9,7.5,Yes,5,12,534142.98

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8368 entries, 0 to 8367
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    8368 non-null   object
 1   Location                8368 non-null   object
 2   Cuisine                 8368 non-null   object
 3   Rating                  8368 non-null   float64
 4   Seating Capacity        8368 non-null   int64
 5   Average Meal Price      8368 non-null   float64
 6   Marketing Budget        8368 non-null   int64
 7   Social Media Followers  8368 non-null   int64
 8   Chef Experience Years   8368 non-null   int64
 9   Number of Reviews       8368 non-null   int64
 10  Avg Review Length       8368 non-null   float64
 11  Ambience Score          8368 non-null   float64
 12  Service Quality Score   8368 non-null   float64
 13  Parking Availability    8368 non-null   object
 14  Weekend Reservations    8368 non-null   int64
 15  Weekday Reservations    8368 non-null   int64
 16  Revenue                 8368 non-null   float64
dtypes: float64(6), int64(7), object(4)
memory usage: 1.1+ MB

In [79]:
df.isnull().sum()

Name                      0
Location                  0
Cuisine                   0
Rating                    0
Seating Capacity          0
Average Meal Price        0
Marketing Budget          0
Social Media Followers    0
Chef Experience Years     0
Number of Reviews         0
Avg Review Length         0
Ambience Score            0
Service Quality Score     0
Parking Availability      0
Weekend Reservations      0
Weekday Reservations      0
Revenue                   0
dtype: int64

In [80]:
df.head()

,Name,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Marketing Budget,Social Media Followers,Chef Experience Years,Number of Reviews,Avg Review Length,Ambience Score,Service Quality Score,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,Restaurant 0,Rural,Japanese,4.0,38,73.98,2224,23406,13,185,161.924906,1.3,7.0,Yes,13,4,638945.52
1,Restaurant 1,Downtown,Mexican,3.2,76,28.11,4416,42741,8,533,148.759717,2.6,3.4,Yes,48,6,490207.83
2,Restaurant 2,Rural,Italian,4.7,48,48.29,2796,37285,18,853,56.849189,5.3,6.7,No,27,14,541368.62
3,Restaurant 3,Rural,Italian,4.4,34,51.55,1167,15214,13,82,205.433265,4.6,2.8,Yes,9,17,404556.80
4,Restaurant 4,Downtown,Japanese,4.9,88,75.98,3639,40171,9,78,241.681584,8.6,2.1,No,37,26,1491046.35

In [81]:
df=df.drop(['Name','Avg Review Length', 'Ambience Score', 'Service Quality Score', 'Marketing Budget'], axis=1)
df.head()

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,Rural,Japanese,4.0,38,73.98,23406,13,185,Yes,13,4,638945.52
1,Downtown,Mexican,3.2,76,28.11,42741,8,533,Yes,48,6,490207.83
2,Rural,Italian,4.7,48,48.29,37285,18,853,No,27,14,541368.62
3,Rural,Italian,4.4,34,51.55,15214,13,82,Yes,9,17,404556.80
4,Downtown,Japanese,4.9,88,75.98,40171,9,78,No,37,26,1491046.35

In [82]:
df['Average Meal Price']= df['Average Meal Price']*10
df['Revenue']= df['Revenue']*83.5

In [83]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,Rural,Japanese,4.0,38,739.8,23406,13,185,Yes,13,4,5.335195e+07
1,Downtown,Mexican,3.2,76,281.1,42741,8,533,Yes,48,6,4.093235e+07
2,Rural,Italian,4.7,48,482.9,37285,18,853,No,27,14,4.520428e+07
3,Rural,Italian,4.4,34,515.5,15214,13,82,Yes,9,17,3.378049e+07
4,Downtown,Japanese,4.9,88,759.8,40171,9,78,No,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,Suburban,Indian,3.4,54,348.5,11298,11,380,Yes,37,0,3.629356e+07
8364,Rural,Indian,3.7,49,368.8,20432,9,713,No,37,21,3.465066e+07
8365,Downtown,Italian,4.7,88,468.7,63945,6,436,Yes,83,21,7.768806e+07
8366,Rural,American,3.1,31,445.3,7170,1,729,No,6,21,2.600971e+07
8367,Rural,Japanese,4.0,33,710.7,24268,8,197,Yes,5,12,4.460094e+07

In [84]:
df['Cuisine'].value_counts()

Cuisine
French      1433
American    1416
Italian     1413
Mexican     1393
Indian      1369
Japanese    1344
Name: count, dtype: int64

In [85]:
df['Location'].value_counts()

Location
Downtown    2821
Suburban    2785
Rural       2762
Name: count, dtype: int64

In [86]:
df['Location'] = df['Location'].replace('Downtown', 'Urban')

In [87]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,Rural,Japanese,4.0,38,739.8,23406,13,185,Yes,13,4,5.335195e+07
1,Urban,Mexican,3.2,76,281.1,42741,8,533,Yes,48,6,4.093235e+07
2,Rural,Italian,4.7,48,482.9,37285,18,853,No,27,14,4.520428e+07
3,Rural,Italian,4.4,34,515.5,15214,13,82,Yes,9,17,3.378049e+07
4,Urban,Japanese,4.9,88,759.8,40171,9,78,No,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,Suburban,Indian,3.4,54,348.5,11298,11,380,Yes,37,0,3.629356e+07
8364,Rural,Indian,3.7,49,368.8,20432,9,713,No,37,21,3.465066e+07
8365,Urban,Italian,4.7,88,468.7,63945,6,436,Yes,83,21,7.768806e+07
8366,Rural,American,3.1,31,445.3,7170,1,729,No,6,21,2.600971e+07
8367,Rural,Japanese,4.0,33,710.7,24268,8,197,Yes,5,12,4.460094e+07

In [88]:
df['Location'].value_counts()

Location
Urban       2821
Suburban    2785
Rural       2762
Name: count, dtype: int64

In [89]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [90]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,Rural,Japanese,4.0,38,739.8,23406,13,185,Yes,13,4,5.335195e+07
1,Urban,Mexican,3.2,76,281.1,42741,8,533,Yes,48,6,4.093235e+07
2,Rural,Italian,4.7,48,482.9,37285,18,853,No,27,14,4.520428e+07
3,Rural,Italian,4.4,34,515.5,15214,13,82,Yes,9,17,3.378049e+07
4,Urban,Japanese,4.9,88,759.8,40171,9,78,No,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,Suburban,Indian,3.4,54,348.5,11298,11,380,Yes,37,0,3.629356e+07
8364,Rural,Indian,3.7,49,368.8,20432,9,713,No,37,21,3.465066e+07
8365,Urban,Italian,4.7,88,468.7,63945,6,436,Yes,83,21,7.768806e+07
8366,Rural,American,3.1,31,445.3,7170,1,729,No,6,21,2.600971e+07
8367,Rural,Japanese,4.0,33,710.7,24268,8,197,Yes,5,12,4.460094e+07

In [91]:
df['Location']= df['Location'].map({'Rural': 2, 'Suburban':1, 'Urban': 0})

In [92]:
df['Cuisine'].value_counts()

Cuisine
French      1433
American    1416
Italian     1413
Mexican     1393
Indian      1369
Japanese    1344
Name: count, dtype: int64

In [93]:
df['Cuisine']= df['Cuisine'].map({'Indian': 0.6, 'Italian':0.5, 'American': 0.4, 'French': 0.3, 'Mexican': 0.2, 'Japanese': 0.1})
df['Parking Availability']= df['Parking Availability'].map({'Yes': 1, 'No':0})

In [94]:
df['Cuisine'].value_counts()

Cuisine
0.3    1433
0.4    1416
0.5    1413
0.2    1393
0.6    1369
0.1    1344
Name: count, dtype: int64

In [95]:
df.corr()['Revenue']

Location                 -0.636118
Cuisine                  -0.295534
Rating                    0.009899
Seating Capacity          0.677317
Average Meal Price        0.686365
Social Media Followers    0.354466
Chef Experience Years     0.026899
Number of Reviews        -0.008233
Parking Availability     -0.003548
Weekend Reservations      0.292400
Weekday Reservations      0.273284
Revenue                   1.000000
Name: Revenue, dtype: float64

In [96]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,2,0.1,4.0,38,739.8,23406,13,185,1,13,4,5.335195e+07
1,0,0.2,3.2,76,281.1,42741,8,533,1,48,6,4.093235e+07
2,2,0.5,4.7,48,482.9,37285,18,853,0,27,14,4.520428e+07
3,2,0.5,4.4,34,515.5,15214,13,82,1,9,17,3.378049e+07
4,0,0.1,4.9,88,759.8,40171,9,78,0,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,1,0.6,3.4,54,348.5,11298,11,380,1,37,0,3.629356e+07
8364,2,0.6,3.7,49,368.8,20432,9,713,0,37,21,3.465066e+07
8365,0,0.5,4.7,88,468.7,63945,6,436,1,83,21,7.768806e+07
8366,2,0.4,3.1,31,445.3,7170,1,729,0,6,21,2.600971e+07
8367,2,0.1,4.0,33,710.7,24268,8,197,1,5,12,4.460094e+07

In [97]:
df.describe()

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
count,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8368.000000,8.368000e+03
mean,0.992949,0.351004,4.008258,60.212835,478.966587,36190.621773,10.051984,523.010397,0.500598,29.491754,29.235301,5.478189e+07
std,0.816832,0.169297,0.581474,17.399488,143.367667,18630.153330,5.516606,277.215127,0.500030,20.025415,20.004277,2.232905e+07
min,0.000000,0.100000,3.000000,30.000000,250.000000,5277.000000,1.000000,50.000000,0.000000,0.000000,0.000000,1.542316e+07
25%,0.000000,0.200000,3.500000,45.000000,354.900000,22592.500000,5.000000,277.000000,0.000000,13.000000,13.000000,3.796339e+07
50%,1.000000,0.400000,4.000000,60.000000,455.350000,32518.500000,10.000000,528.000000,1.000000,27.000000,26.000000,5.045421e+07
75%,2.000000,0.500000,4.500000,75.000000,603.000000,44566.250000,15.000000,764.250000,1.000000,43.000000,43.000000,6.789337e+07
max,2.000000,0.600000,5.000000,90.000000,760.000000,103777.000000,19.000000,999.000000,1.000000,88.000000,88.000000,1.279109e+08

In [103]:
X = df.drop(columns=['Revenue'])

In [102]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,2,0.1,4.0,38,739.8,23406,13,185,1,13,4,5.335195e+07
1,0,0.2,3.2,76,281.1,42741,8,533,1,48,6,4.093235e+07
2,2,0.5,4.7,48,482.9,37285,18,853,0,27,14,4.520428e+07
3,2,0.5,4.4,34,515.5,15214,13,82,1,9,17,3.378049e+07
4,0,0.1,4.9,88,759.8,40171,9,78,0,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,1,0.6,3.4,54,348.5,11298,11,380,1,37,0,3.629356e+07
8364,2,0.6,3.7,49,368.8,20432,9,713,0,37,21,3.465066e+07
8365,0,0.5,4.7,88,468.7,63945,6,436,1,83,21,7.768806e+07
8366,2,0.4,3.1,31,445.3,7170,1,729,0,6,21,2.600971e+07
8367,2,0.1,4.0,33,710.7,24268,8,197,1,5,12,4.460094e+07

In [109]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,2,0.1,4.0,38,739.8,23406,13,185,1,13,4,5.335195e+07
1,0,0.2,3.2,76,281.1,42741,8,533,1,48,6,4.093235e+07
2,2,0.5,4.7,48,482.9,37285,18,853,0,27,14,4.520428e+07
3,2,0.5,4.4,34,515.5,15214,13,82,1,9,17,3.378049e+07
4,0,0.1,4.9,88,759.8,40171,9,78,0,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,1,0.6,3.4,54,348.5,11298,11,380,1,37,0,3.629356e+07
8364,2,0.6,3.7,49,368.8,20432,9,713,0,37,21,3.465066e+07
8365,0,0.5,4.7,88,468.7,63945,6,436,1,83,21,7.768806e+07
8366,2,0.4,3.1,31,445.3,7170,1,729,0,6,21,2.600971e+07
8367,2,0.1,4.0,33,710.7,24268,8,197,1,5,12,4.460094e+07

In [107]:
df.head(10)

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,2,0.1,4.0,38,739.8,23406,13,185,1,13,4,5.335195e+07
1,0,0.2,3.2,76,281.1,42741,8,533,1,48,6,4.093235e+07
2,2,0.5,4.7,48,482.9,37285,18,853,0,27,14,4.520428e+07
3,2,0.5,4.4,34,515.5,15214,13,82,1,9,17,3.378049e+07
4,0,0.1,4.9,88,759.8,40171,9,78,0,37,26,1.245024e+08
5,0,0.6,4.4,79,356.9,75378,5,400,1,27,22,5.379245e+07
6,2,0.2,4.9,49,353.0,32587,11,106,0,12,28,3.342911e+07
7,1,0.1,4.1,61,736.5,33429,14,377,0,56,23,8.468183e+07
8,2,0.1,4.2,37,737.5,37102,18,494,1,27,24,5.307311e+07
9,2,0.3,5.0,32,598.0,28419,18,907,0,12,19,3.781887e+07

In [65]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations
0,1.232947,-1.482710,-0.014202,-1.276714,1.819441,-0.686274,0.534421,-1.219380,0.998806,-0.823590,-1.261571
1,-1.215683,-0.891998,-1.390099,0.907389,-1.380216,0.351622,-0.371987,0.036038,0.998806,0.924293,-1.161586
2,1.232947,0.880138,1.189708,-0.701950,0.027437,0.058746,1.440830,1.190445,-1.001196,-0.124437,-0.761648
3,1.232947,0.880138,0.673746,-1.506619,0.254838,-1.126017,0.534421,-1.590955,0.998806,-1.023349,-0.611671
4,-1.215683,-1.482710,1.533682,1.597106,1.958951,0.213665,-0.190705,-1.605385,-1.001196,0.374958,-0.161740
...,...,...,...,...,...,...,...,...,...,...,...
8363,0.008632,1.470850,-1.046125,-0.357091,-0.910068,-1.336227,0.171858,-0.515913,0.998806,0.374958,-1.461540
8364,1.232947,1.470850,-0.530163,-0.644473,-0.768466,-0.845917,-0.190705,0.685392,-1.001196,0.374958,-0.411702
8365,-1.215683,0.880138,1.189708,1.597106,-0.071614,1.489845,-0.734551,-0.313892,0.998806,2.672176,-0.411702
8366,1.232947,0.289426,-1.562086,-1.679048,-0.234841,-1.557816,-1.640959,0.743112,-1.001196,-1.173167,-0.411702
8367,1.232947,-1.482710,-0.014202,-1.564095,1.616454,-0.640002,-0.371987,-1.176090,0.998806,-1.223107,-0.861632

In [110]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X, y = df.drop(['Revenue'], axis=1), df['Revenue']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [111]:
X_train.shape

(6694, 11)

In [112]:
X_test.shape

(1674, 11)

In [113]:
y_train.shape

(6694,)

In [115]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [116]:
linear_reg = LinearRegression()
decision_tree = DecisionTreeRegressor(random_state=42)
random_forest = RandomForestRegressor(random_state=42)

In [117]:
linear_reg.fit(X_train, y_train)

LinearRegression()

In [118]:
decision_tree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [119]:


random_forest.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [120]:
y_pred_linear = linear_reg.predict(X_test)
y_pred_tree = decision_tree.predict(X_test)
y_pred_forest = random_forest.predict(X_test)

In [121]:
print("Linear Regression:")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_linear)}")
print(f"R^2 Score: {r2_score(y_test, y_pred_linear)}\n")

Linear Regression:
Mean Squared Error: 19182970019746.63
R^2 Score: 0.9612629135005717

In [122]:
print("Decision Tree Regression:")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_tree)}")
print(f"R^2 Score: {r2_score(y_test, y_pred_tree)}\n")

Decision Tree Regression:
Mean Squared Error: 1604214671588.3513
R^2 Score: 0.9967605327833489

In [123]:
print("Random Forest Regression:")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_forest)}")
print(f"R^2 Score: {r2_score(y_test, y_pred_forest)}")

Random Forest Regression:
Mean Squared Error: 376862575347.2569
R^2 Score: 0.999238983423078

In [124]:
import pickle

In [125]:
with open('random_forest_model.pkl', 'wb') as f:
    pickle.dump(random_forest, f)

In [126]:
with open('random_forest_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

In [127]:
df

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations,Revenue
0,2,0.1,4.0,38,739.8,23406,13,185,1,13,4,5.335195e+07
1,0,0.2,3.2,76,281.1,42741,8,533,1,48,6,4.093235e+07
2,2,0.5,4.7,48,482.9,37285,18,853,0,27,14,4.520428e+07
3,2,0.5,4.4,34,515.5,15214,13,82,1,9,17,3.378049e+07
4,0,0.1,4.9,88,759.8,40171,9,78,0,37,26,1.245024e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
8363,1,0.6,3.4,54,348.5,11298,11,380,1,37,0,3.629356e+07
8364,2,0.6,3.7,49,368.8,20432,9,713,0,37,21,3.465066e+07
8365,0,0.5,4.7,88,468.7,63945,6,436,1,83,21,7.768806e+07
8366,2,0.4,3.1,31,445.3,7170,1,729,0,6,21,2.600971e+07
8367,2,0.1,4.0,33,710.7,24268,8,197,1,5,12,4.460094e+07

In [128]:
X_test

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations
4794,0,0.2,4.1,81,353.2,40081,16,449,0,2,1
5505,0,0.6,4.5,78,375.5,90112,6,752,0,61,12
5159,2,0.6,3.0,43,346.6,19056,18,306,0,29,0
8140,0,0.6,4.8,78,389.9,55863,11,781,0,35,28
7790,1,0.6,3.8,60,325.7,29713,7,271,1,10,42
...,...,...,...,...,...,...,...,...,...,...,...
8155,1,0.1,3.1,52,757.2,19192,3,211,1,41,27
1815,2,0.4,4.8,32,356.2,37855,14,921,0,29,1
1053,0,0.3,3.1,75,553.0,54454,19,265,1,54,6
4327,1,0.5,4.6,58,495.6,48452,4,453,0,28,54
3493,2,0.1,4.6,33,654.6,29043,3,832,1,16,12

In [134]:
import pandas as pd
import pickle


sample_data = pd.DataFrame({
    'Location': ['Rural'],
    'Cuisine': ['Mexican'],
    'Rating': [4.1],
    'Seating Capacity': [81],
    'Average Meal Price': [353.2],
    'Social Media Followers': [40081],
    'Chef Experience Years': [16],
    'Number of Reviews': [449],
    'Parking Availability': ['No'],
    'Weekend Reservations': [2],
    'Weekday Reservations': [1]
})


sample_data

,Location,Cuisine,Rating,Seating Capacity,Average Meal Price,Social Media Followers,Chef Experience Years,Number of Reviews,Parking Availability,Weekend Reservations,Weekday Reservations
0,Rural,Mexican,4.1,81,353.2,40081,16,449,No,2,1

In [ ]:
# Encoding 'Cuisine'
cuisine_encoding = {'Italian': 0.5, 'American': 0.4, 'Indian': 0.6, 'Mexican': 0.2, 'French': 0.3, 'Japan': 0.1}
sample_data['Cuisine_Encoded'] = sample_data['Cuisine'].map(cuisine_encoding)
sample_data.drop(columns=['Cuisine'], inplace=True)

# Encoding 'Location'
location_encoding = {'Rural': 0, 'Urban': 2, 'SemiUrban': 1}
sample_data['Location_Encoded'] = sample_data['Location'].map(location_encoding)
sample_data.drop(columns=['Location'], inplace=True)

# Encoding 'Parking Availability'
parking_encoding = {'Yes': 1, 'No': 0}
sample_data['Parking_Encoded'] = sample_data['Parking Availability'].map(parking_encoding)
sample_data.drop(columns=['Parking Availability'], inplace=True)

# Load the saved model from file
with open('random_forest_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)



# Ensure the sample data columns match the model's expected input
sample_data = sample_data[['Location_Encoded', 'Cuisine_Encoded', 'Rating', 'Seating Capacity', 
                           'Average Meal Price', 'Social Media Followers', 'Chef Experience Years', 
                           'Number of Reviews', 'Parking_Encoded', 'Weekend Reservations', 'Weekday Reservations']]



# Make predictions using the loaded model and scaled sample data
predictions = loaded_model.predict(sample_data)

print("Predictions:", predictions)

In [136]:
import pandas as pd
import pickle

# Sample data with lists for single row DataFrame
sample_data = pd.DataFrame({
    'Location': ['Rural'],
    'Cuisine': ['Mexican'],
    'Rating': [4.1],
    'Seating Capacity': [81],
    'Average Meal Price': [353.2],
    'Social Media Followers': [40081],
    'Chef Experience Years': [16],
    'Number of Reviews': [449],
    'Parking Availability': ['No'],
    'Weekend Reservations': [2],
    'Weekday Reservations': [1]
})

# Encoding 'Cuisine'
cuisine_encoding = {'Italian': 0.5, 'American': 0.4, 'Indian': 0.6, 'Mexican': 0.2, 'French': 0.3, 'Japan': 0.1}
sample_data['Cuisine'] = sample_data['Cuisine'].map(cuisine_encoding)


# Encoding 'Location'
location_encoding = {'Rural': 0, 'Urban': 2, 'SemiUrban': 1}
sample_data['Location'] = sample_data['Location'].map(location_encoding)

# Encoding 'Parking Availability'
parking_encoding = {'Yes': 1, 'No': 0}
sample_data['Parking Availability'] = sample_data['Parking Availability'].map(parking_encoding)

# Load the saved model from file
with open('random_forest_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

# Ensure the sample data columns match the model's expected input
sample_data = sample_data[['Location', 'Cuisine', 'Rating', 'Seating Capacity', 
                           'Average Meal Price', 'Social Media Followers', 'Chef Experience Years', 
                           'Number of Reviews', 'Parking Availability', 'Weekend Reservations', 'Weekday Reservations']]

# Make predictions using the loaded model and sample data
predictions = loaded_model.predict(sample_data)

print("Predictions:", predictions)

Predictions: [54988181.33230001]